spring:
  application:
    name: bpkad-kepegawaian
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bpkad_kepegawaian
    username: postgres
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 2 # low pool size since we're using virtual threads
  jpa:
    defer-datasource-initialization: true # JPA waits for Flyway first
    hibernate:
      ddl-auto: none # Flyway handles schema
    properties:
      org.hibernate:
        dialect: org.hibernate.community.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  threads:
    virtual:
      enabled: true

server:
  tomcat:
    threads:
      max: 1 # minimal threads since virtual threads handle the load

application:
  security:
    token:
      ttl: ${TOKEN_TTL:86400} # 24 hours in seconds
